### ISSUE TITLE
confirmation delete 

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#11]
As a **user** I can **ignore the deletion** so that **I have the chance to keep my appointment**

 **Acceptance criteria**

- [x] After the user clicks on the delete button, the user receives a confirmation message.
- [x] The user can decide either to keep the appointment or delete it. 

**Task**

- [x] Paragraph asks the user that the user is sure to delete the appointment.
- [x] Create two buttons inside the confirmation message, one deleted and the other sent back to the home page
