### ISSUE TITLE
new function for the user to see their action

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#12]
As a **user** I can  **click on the booked appointment link** so that  **I can see my appointment any time**

**Acceptance criteria** 

- [x] Click on the link at the top of the appointment page
- [x] The link attaches with info on the users' appointment

**Task**

- [x] Add a link at the top of the appointment page that converts the user to a message page
