### ISSUE TITLE
Restrict users value 

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#13]
As a **user** I can **book an available appointment** so that **nobody interferes the appointment**

**- Acceptance criteria A**
- [x] As the user books an available appointment in terms of time and date.

**- Acceptance criteria B**
- [x] As a user I can book one appointment at a time

**Tasks**

- [x] Rais validation error in the form.py
- [x] Includes the error in the template of appointment and editing.
