### ISSUE TITLE
make or delete an appointment 

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#3]
EPIC: book an appointment, Edit an appointment, or Delete an appointment

As a **User**, I can **book, edit, or delete an appointment** so that **I have flexibility**.

**Acceptance Criteria**

- [x] Having different choices, book, edit, or delete an appointment.
- [x] sign-in is required to access the booking system.

**Tasks**

- [x]  A form for the booking system.
- [x]  Create a Booking system that includes the customer's pet name, date, and time. 
- [x] The booking system includes booking, edition, or deletion, and confirmation messages.
- [x] A template for booking or deletion.
- [x]  A view for booking or deletion.
