### ISSUE TITLE
Booking system

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#4]
Epic: Users can check the bookings

USER STORY: As a **User**, I can **go to profile** so that **I can make an appointment**

**Acceptance Criteria**

- [x] After the users log in, they can access the booking system.
- [x] Then they can book their appointment.

**Tasks**

- [x]  A panel asks the user to enter their info.
