### ISSUE TITLE
Create an account 

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#5]
EPIC: Users can create an account 

USER STORY: As a **User** I can **create an account**  so that **I can log in**.

**Acceptance Criteria**

- [x]  Users can create an account
- [x]  Then the users can log in to their Profile

**Tasks**

- [x] Create sign-in, log in  and log out.
