### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#6]
EPIC: Navigate the home page easily

USER STORY: As a **user** I can **easily navigate from the home page**  so that **I can access whatever I want without confusion**

**Acceptance Criteria**

- [x] Main text about the clinic.
- [x] Create a button in the main text, that the user signs up from

**Tasks**
  - [x]  text about the vet clinic.
  - [x] add Animation style
