### ISSUE TITLE
sign up page

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#8]
Epic: Sign up to create a user page
As a **User** I can **sign up** so that **I can have my own profile**

 **Acceptance criteria** 

- [x] singing up form.
- [x] receiving message of the info.

**tasks**

- [x] sign-up form.
- [x] clear and submission button.
