### ISSUE TITLE
authorization

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/PP4#9]
Epic: Log in  to create a profile
As a **User** I can **sign up** so that **I have an account to be able to book an appointment**

 **Acceptance criteria** 

- [x] User can sign up then 
- [x] Log in then.
- [x] access the user profile.
- [x] then book the appointment.

**tasks**

- [x] Download Allauth
- [x] Inherent to all accounts are going to be used in this project.
